import Head from "next/head";

import CommonLayout from "@/layouts/CommonLayout";
import SwiperLg from "@/components/custom/SwiperLg";
import BannerSwiper from "@/components/custom/BannerSwiper";
import BookSubCategory from "@/components/custom/BookSubCategory";

import booksDataBase from "@/database/db";
import banners from "@/database/banners";

import { Banner, Book } from "@/types";

interface Props {
  allBooks: Book[];
  allBanners: Banner[];
}

export const getStaticProps = () => {
  const allBooks = booksDataBase;
  const allBanners = banners;

  return {
    props: { allBooks, allBanners },
    revalidate: 60 * 60,
  };
};

const Home: React.FC<Props> = ({ allBooks, allBanners }) => {
  return (
    <>
      <Head>
        <title>پردیس کتاب</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/logo.svg" />
      </Head>

      <CommonLayout>
        <SwiperLg />
        <BookSubCategory subCategory="توسعه فردی" books={allBooks} />
        <BannerSwiper category="blog" banners={allBanners} />
        <BookSubCategory subCategory="خانواده و ازدواج" books={allBooks} />
        <BannerSwiper category="quote" banners={allBanners} />
        <BookSubCategory subCategory="داستان خارجی" books={allBooks} />
        <BannerSwiper category="instagram" banners={allBanners} />
        <BookSubCategory subCategory="داستان ایرانی" books={allBooks} />
      </CommonLayout>
    </>
  );
};

export default Home;
