import { useEffect } from "react";

import Head from "next/head";

import CommonLayout from "@/layouts/CommonLayout";
import SwiperLg from "@/components/custom/SwiperLg";
import BannerSwiper from "@/components/custom/BannerSwiper";
import BookSubCategory from "@/components/custom/BookSubCategory";

import { useTypedDispatch, useTypedSelector } from "@/redux/store";
import { fetchBooks } from "@/redux/slices/booksSlice";
import { fetchBanners } from "@/redux/slices/bannersSlice";

const Home: React.FC = () => {
  const books = useTypedSelector((store) => store.books.value);
  const banners = useTypedSelector((store) => store.banners.value);
  const dispatch = useTypedDispatch();

  useEffect(() => {
    dispatch(fetchBooks());
    dispatch(fetchBanners());
  }, []);

  return (
    <>
      <Head>
        <title>طاقچه | فروشگاه کتاب</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/logo.svg" />
      </Head>

      <CommonLayout>
        <SwiperLg />
        <BookSubCategory subCategory="توسعه فردی" books={books} />
        <BannerSwiper category="blog" banners={banners} />
        <BookSubCategory subCategory="خانواده و ازدواج" books={books} />
        <BannerSwiper category="quote" banners={banners} />
        <BookSubCategory subCategory="داستان خارجی" books={books} />
        <BannerSwiper category="instagram" banners={banners} />
        <BookSubCategory subCategory="داستان ایرانی" books={books} />
      </CommonLayout>
    </>
  );
};

export default Home;
